### ISSUE TITLE
The item browser for the developmental version exploded.

### ISSUE THREAD

**Issue by AllisonBW** [Sheco/cdda-itembrowser#1]
It looks like a whole bunch of things are pointing to the wrong places, and some terms give errors when searching for them (like "woods soup".)

Recipes are referring to completely inappropriate tools, ingredients, books, and values, like the stone knife now calling for 4 ranks of Mechanics, wanting to use tools like 150 charges of vacuum-packed salted simpleton slices.and XL gas masks, wanting to use ingredients like steel drums and chains.

**Comment by Barhandar** [comment]
It's also showing Version: 0.B-2702-gd177b33 when the CDDA git is up to 0.B-2931-gc8a8bbc, and some up-to-date items (like sealed soup) are visible.

**Comment by Sheco** [comment]
Thank you for reporting this, there was an issue when recompiling the database, I've fixed it.

Could you try again now?

**Comment by AllisonBW** [comment]
I checked and it's working. Thank you for the item browser, Sheco. :)
