### ISSUE TITLE
TOOL_ARMOR isn't displayed in CLOTHING

### ISSUE THREAD

**Issue by Nandorianen** [Sheco/cdda-itembrowser#11]
Some time ago new item type was added for activatable armor like mining helmets and scarves. I just noticed that the list of clothing does not get items from tool_armor.json.
Can't think of a good reason not to, so I suggest changing that.

**Comment by Sheco** [comment]
That's interesting, I haven't played the game in a long time, hence the item browser can be a bit outdated in parts, your feedback is extremely invaluable.

About this, the clothing catalog is indexed based on the "covers" variable, currently only for items whose type is "ARMOR", I can see these items have a type of "TOOL_ARMOR".

This patch should achieve what you are looking for, please check it.

**Comment by Nandorianen** [comment]
Works as expected. Thanks!
Nice to see you care. For a while it looked like you lost interest. Guess this place just needs more visitors?) Maybe making a sticky thread somewhere on the forums would bring more feedback if you are looking for it. Relatively few people go to github for this kind of thing.

**Comment by Sheco** [comment]
I just stopped playing, but I'm happy with the item browser and I can improve it as long as the ideas/suggestions keep coming and I have the time to work on this.

**Comment by Nandorianen** [comment]
Oh, I just noticed item properties screen also doesn't give any clothing info for TOOL_ARMOR type.

**Comment by Sheco** [comment]
Good catch, that's now fixed.

**Comment by Nandorianen** [comment]
It's whack-a-bug time!
Now pages for clothing that doesn't cover anything won't load. Try colored belts or jewellery, you should get an error.

**Comment by Nandorianen** [comment]
And now it works. That was quick.

**Comment by Sheco** [comment]
Thank you for thorough testing, Nandorianen

**Comment by Nandorianen** [comment]
I feel like I am pestering you with constant requests. If I get on your nerves, just say the word.

**Comment by Sheco** [comment]
You're doing great, I'm taking a shot at the easiest issues, no need to worry.

**Comment by Sheco** [comment]
mm I kind of broke this, fixing #12, on commit c5e46c734dc536572614094031ee9ff0f4cd3cb6 ... I forgot about this feature.

I'll fix this later.
