### ISSUE TITLE
Some misc items not opening

### ISSUE THREAD

**Issue by Nandorianen** [Sheco/cdda-itembrowser#12]
For example, cell phones and umbrellas. I can't figure out what's wrong with them, since similar items like pocket watch or money bundle are opening normally.

**Comment by Nandorianen** [comment]
Survivor helmet works normally, heavy survivor helmet doesn't. Weird stuff is going on.

**Comment by remyroy** [comment]
Same goes for [knife spear](http://cdda-trunk.estilofusion.com/spear_knife)

**Comment by Sheco** [comment]
I see! that was actually a different scenario, iron items can be cut now, I see, that was not there before.

That broke something up, it's now fixed, thanks!

**Comment by remyroy** [comment]
This item still does not work: http://cdda-trunk.estilofusion.com/helmet_hsurvivor

**Comment by SomewhatNihilist** [comment]
Atomic Lamp, -nightlinght, -coffee maker and -battery mod are broken: http://cdda-trunk.estilofusion.com/search?q=atomic

**Comment by Sheco** [comment]
Hello I now see the problem, and how my previous patch was rushed and incorrect.

This latest commit now fixes these errors now that I see the pattern. This was probably broken for a long time, which is unfortunate, hopefully this is the last of these errors.

Thank you guys.

**Comment by Nandorianen** [comment]
Thank you.
