### ISSUE TITLE
Magazines

### ISSUE THREAD

**Issue by Mattamue** [Sheco/cdda-itembrowser#15]
Hey there, I'm not savvy enough to know where to start, but there have been some changes recently with magazines that have created new file names and, I think, a different directory structure. Could this be reviewed to update for the item browser?

IE \data\json\items\magazines.json in the most recent experimental has items that aren't coming up in the search.

**Comment by Sheco** [comment]
All right, the item browser will now index items of type "MAGAZINE" thank you for your report.

I'll push the code into the server in some minutes, fixing some other issues I found.
