### ISSUE TITLE
Weird results browsing the development version of the database

### ISSUE THREAD

**Issue by tivec** [Sheco/cdda-itembrowser#2]
There seems to be some inconsistency with the development database vs stable.

A good example is http://cdda-trunk.estilofusion.com/reflexrecurvebow/craft in which you see that the reflex recurve bow requires "1 tool with platinum gas discount card quality of 1".

Another sample is going to http://cdda-trunk.estilofusion.com/morningstar/craft. This one seems alright, except that the recipe is definitely not found in 101 Wrestling moves. If you go to that, you get http://cdda-trunk.estilofusion.com/manual_brawl, which according to the view is the Zombie Survival Guide. If you click on "recipes" here, you get recipes from a seemingly random book instead. Going back to view item gives you another book.

Strawberry jam, http://cdda-trunk.estilofusion.com/jam_strawberries/craft, states that you need a tool called "http://cdda-trunk.estilofusion.com/trash_forest", but that one points to nothing in the database.

**Comment by Sheco** [comment]
Thank you for your report.

It's the same thing as the previous reported issue, it's nothing crazy, but I have to fix the root of the problem that causes this behaviour.

For now, the database is fixed.

**Comment by tivec** [comment]
Cheers, seems to be sorted now :)

**Comment by slitherrr** [comment]
I can report similar goings-on.

Do this search: http://cdda-trunk.estilofusion.com/search?q=wired+sheet
The only result is "fancy table". Click it (to here: http://cdda-trunk.estilofusion.com/v_table), and the result page says "King James Bible"

**Comment by Sheco** [comment]
Ok, I resolved this again, thank you for reporting this.

I have to fix this, I know what's the problem but I haven't been able to do it, I'm sorry.

**Comment by Sheco** [comment]
This should now be fixed in 11d596df235eb45f1821b36e55f5e8f3aef732a0

Hopefully this won't happen again :)
