### ISSUE TITLE
Monster tag not listed on monster page.

### ISSUE THREAD

**Issue by Soyweiser** [Sheco/cdda-itembrowser#5]
If you look at this page: http://cdda.estilofusion.com/monsters/mon_jabberwock you cannot easily find the monster tag. Only in the url is it visible. Which makes its a little bit harder for people to find the monster tag of a monster.

**Comment by Sheco** [comment]
Does this look like something you would like to see?

![screen shot 2015-06-05 at 9 05 18 am](https://cloud.githubusercontent.com/assets/4542662/8010078/15d172f2-0b62-11e5-890d-e358310b20b9.png)

**Comment by Soyweiser** [comment]
Yeah totally. Was it already in and I missed it?

**Comment by Soyweiser** [comment]
Unrelated. But I was planning om adding direct links to the monsterbrowser from the monster template on the wiki.

**Comment by Sheco** [comment]
No, it's not already there, the screenshot is from my dev copy. I'll push it to the servers if you like that.

**Comment by Sheco** [comment]
This change has now been deployed.

About linking the monsters on the wiki, that's great, I've always thought both the wiki and the item browser should have links to each other. (But I don't have the time to update the wiki)

**Comment by Soyweiser** [comment]
Took some fiddling, but monster templates now have links to the monsterbrowser on the sidebar. As seen here: www.wiki.cataclysmdda.com/index.php?title=Shoggoth

Now all the monster pages need to be updated... (which creator-unreal is helping with from irc)

Thanks for fixing the issue!
