### ISSUE TITLE
Health value is not displayed in comestibles catalog

### ISSUE THREAD

**Issue by Nandorianen** [Sheco/cdda-itembrowser#7]
Probably a typo somewhere, like trying to read "health" instead of "healthy".
On specific item pages "healthy" is displayed properly.

**Comment by Sheco** [comment]
You're completely right, it's now fixed in 257220f169f5ae88e76085519a61a650d5803837, thanks!

**Comment by Nandorianen** [comment]
That was quick. Thanks!
